### PR TITLE
Added feature to maximize/restore windows

### LINKED ISSUE #28: Add ability to maximize / restore browser windows.
Browsers may open new windows/tabs that only cover part of the screen, we should provide a means of maximizing windows.  We should also provide a means of restoring the window size (typically the middle of the three window control icons).  Minimizing windows is out of scope for now.

### PR DESCRIPTION
**Pull request by dmahajan980**
Resolves #28 

The window size can be maximized and restored using both buttons and joysticks.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
I see the controls to do this, but can't seem to get it to work for any button or thumbstick axis, at least on the mac.

**Comment by the-t-in-rtf** [comment]
The updated mac implementation works well.  As I discussed in chat, the only small issue is that if a window is in my second monitor and I maximise/restore it, it ends up on the primary monitor.

**Comment by the-t-in-rtf** [comment]
I also notice that if I position two windows side by side to perform a comparison and then maximise/restore one, the previous position or size are not preserved.

**Comment by dmahajan980** [comment]
@the-t-in-rtf as we discussed in our chat, I've updated the pull to restore the same dimensions before maximization but I couldn't test it for macOS. It may or may not work as expected. However, I've opened issue #45 for the same and I'll update it if the preservation of dimensions is working correctly.

**Comment by the-t-in-rtf** [comment]
The position has definitely changed, but something is still off.  Restore consistently puts the window nearly offscreen (usually near the bottom of the screen).

**Comment by the-t-in-rtf** [comment]
The position restore is really solid, good work.

**Pull request merged**
